# Generated by Django 3.2.8 on 2021-10-16 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
